name: nextcloud

services:
  db:
    image: mariadb:11.8.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_DATABASE:      ${DB_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER:          ${DB_USER}
      MYSQL_PASSWORD:      ${DB_PASSWORD}
    volumes:
      - ${NEXTCLOUD_BIND_PATH}/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:8.6.2
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  app:
    image: nextcloud:32.0.8
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MYSQL_HOST:                db
      MYSQL_DATABASE:            ${DB_DATABASE_NAME}
      MYSQL_USER:                ${DB_USER}
      MYSQL_PASSWORD:            ${DB_PASSWORD}
      NEXTCLOUD_ADMIN_USER:      ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD:  ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      OVERWRITECLIURL:           ${OVERWRITECLIURL}
      OVERWRITEPROTOCOL:         https
    volumes:
      - ${NEXTCLOUD_BIND_PATH}/app:/var/www/html
      - ${NEXTCLOUD_BIND_PATH}/data:/var/www/html/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  default:
    external: true
    name: proxy
