name: homarr

services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:v1.59.2
    restart: unless-stopped
    networks:
      - proxy_external
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOMARR_BIND_PATH}/appdata:/appdata
    environment:
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}

networks:
  proxy_external:
    external: true
