name: immich

services:
  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    restart: always
    shm_size: 128mb
    networks:
      - immich_internal
    environment:
      POSTGRES_PASSWORD:    ${DB_PASSWORD}
      POSTGRES_USER:        ${DB_USERNAME}
      POSTGRES_DB:          ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE:      'HDD'
    volumes:
      - ${IMMICH_BIND_PATH}/postgres:/var/lib/postgresql/data
    healthcheck:
      disable: false

  redis:
    image: docker.io/valkey/valkey:9@sha256:3b55fbaa0cd93cf0d9d961f405e4dfcc70efe325e2d84da207a0a8e6d8fde4f9
    restart: always
    networks:
      - immich_internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: always
    networks:
      - immich_internal
    env_file:
      - .env
    volumes:
      - ${IMMICH_BIND_PATH}/cache:/cache
    healthcheck:
      disable: false

  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: always
    networks:
      - proxy_external
      - immich_internal
    depends_on:
      - redis
      - database
    env_file:
      - .env
    volumes:
      - ${IMMICH_BIND_PATH}/library:/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      disable: false

networks:
  proxy_external:
    external: true
  immich_internal:
    internal: true
