name: nginx-proxy-manager

services:
  npm:
    image: "jc21/nginx-proxy-manager:2.14.0"
    restart: unless-stopped
    networks:
      - proxy_external
    ports:
      - "80:80"
      - "443:443"
      - "${DASHBOARD_HOST_PORT}:81"
    environment:
      TZ:                     ${TZ}
      INITIAL_ADMIN_EMAIL:    ${INITIAL_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
    volumes:
      - ${NPM_BIND_PATH}/data:/data
      - ${NPM_BIND_PATH}/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  proxy_external:
    external: true
